#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
LIB_SCRIPT_DIR="$SCRIPT_DIR/../libraries"

source "$LIB_SCRIPT_DIR/basic-operations.lib"
import_config_file
DOMAINS=$1
OUTPUT_DIR=$2

if ! check_argument "$DOMAINS" || ! check_argument "$OUTPUT_DIR"; then
    print_error "run-shosubgo.sh expects a comma separated list of domains, and an output directory"
    exit 1
fi

echo -e "⚡ Running Shosubgo against $DOMAINS..."
mkdir -p "$OUTPUT_DIR" || { echo "Failed to create directory: $OUTPUT_DIR"; exit 1; }

DOMAIN_LIST=($(comma_list_to_array "$DOMAINS"))
CMDS=()

for DOMAIN in "${DOMAIN_LIST[@]}"; do
    echo -e "\tRunning against $DOMAIN..."
    OUT_FILE="$OUTPUT_DIR/shosubgo_$DOMAIN.txt"
    CMD="shosubgo -d $DOMAIN -s $SHODAN_API_KEY > $OUT_FILE"
    echo $CMD
    CMDS+=("$CMD")
done

if run_async_commands "${CMDS[@]}"; then
    print_success "Shosubgo completed successfully"
else 
    print_error "An error occurred while running Shosubgo"
    exit 1
fi
